import type { AccountsWorkItem, ManagedClient, MonthlyAccountFile } from "./types";

export const demoManagedClients: ManagedClient[] = [
  {
    businessId: "WDG-0051",
    companyCode: "ABCCAFE",
    legalName: "ABC Cafe Sdn Bhd",
    tradingName: "ABC Cafe",
    registrationNumber: "202601234567",
    industry: "F&B - Restaurant / Cafe / QSR",
    financialYearEnd: "12-31",
    sstRegistered: true,
    sstRegistrationNumber: "SST-ABC-001",
    serviceChargeEnabled: true,
    ownerName: "Demo Owner",
    ownerEmail: "owner@example.com",
    ownerPhone: "+60 12-000 0000",
    assignedAccountsExecutive: "Accounts Executive A",
    subscriptionStatus: "active",
    subscriptionStartedAt: "2026-08-01",
    wedgeBooksEnabled: true,
    wedgeClockInEnabled: true,
    banks: [{ id: "bank-1", bankName: "Maybank", accountLabel: "Operating", last4: "4421", currency: "MYR", active: true }],
    employeeCount: 14,
    createdAt: "2026-08-01T00:00:00.000Z",
    updatedAt: "2026-09-10T00:00:00.000Z",
  },
  {
    businessId: "WDG-0052",
    companyCode: "LIMSALON",
    legalName: "Lim Salon Enterprise",
    tradingName: "Lim Salon",
    registrationNumber: "IP0123456-X",
    industry: "Beauty / Salon / Spa",
    financialYearEnd: "12-31",
    sstRegistered: false,
    serviceChargeEnabled: false,
    ownerName: "Demo Owner 2",
    ownerEmail: "owner2@example.com",
    assignedAccountsExecutive: "Accounts Executive B",
    subscriptionStatus: "pilot",
    subscriptionStartedAt: "2026-09-01",
    wedgeBooksEnabled: true,
    wedgeClockInEnabled: true,
    banks: [{ id: "bank-2", bankName: "CIMB", accountLabel: "Main", last4: "7833", currency: "MYR", active: true }],
    employeeCount: 8,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-10T00:00:00.000Z",
  },
];

export const demoMonthlyFiles: MonthlyAccountFile[] = [
  {
    id: "WDG-0051-2026-09",
    businessId: "WDG-0051",
    year: 2026,
    month: 9,
    sales: "complete",
    documents: "review_required",
    payroll: "complete",
    books: "processing",
    bankReconciliation: "exceptions",
    review: "not_started",
    pnl: "not_started",
    missingDocumentCount: 3,
    bankExceptionCount: 6,
    reconciliationDifference: 680,
  },
  {
    id: "WDG-0052-2026-09",
    businessId: "WDG-0052",
    year: 2026,
    month: 9,
    sales: "complete",
    documents: "complete",
    payroll: "complete",
    books: "complete",
    bankReconciliation: "reconciled",
    review: "ready",
    pnl: "ready",
    missingDocumentCount: 0,
    bankExceptionCount: 0,
    reconciliationDifference: 0,
  },
];

export const demoWorkItems: AccountsWorkItem[] = [
  {
    id: "work-1",
    businessId: "WDG-0051",
    monthFileId: "WDG-0051-2026-09",
    severity: "critical",
    title: "Bank reconciliation difference",
    detail: "Maybank ending balance differs from adjusted books by RM680.00.",
    assignedTo: "Accounts Executive A",
    createdAt: "2026-09-10T01:00:00.000Z",
  },
  {
    id: "work-2",
    businessId: "WDG-0051",
    monthFileId: "WDG-0051-2026-09",
    severity: "attention",
    title: "3 supporting documents missing",
    detail: "Client upload is required before September can be closed.",
    assignedTo: "Accounts Executive A",
    createdAt: "2026-09-10T01:05:00.000Z",
  },
  {
    id: "work-3",
    businessId: "WDG-0052",
    monthFileId: "WDG-0052-2026-09",
    severity: "review",
    title: "P&L ready for review",
    detail: "Books and bank are complete. Reviewer can approve September P&L.",
    assignedTo: "Accounts Executive B",
    createdAt: "2026-09-10T01:10:00.000Z",
  },
];
