import type { IndustryPnlTemplate, ManagedAccountIndustry, PnlAccountLine } from "./types";

function line(code: string, label: string, group: PnlAccountLine["group"]): PnlAccountLine {
  return { code, label, group };
}

function standardCorporateOpex(): PnlAccountLine[] {
  return [
    line("ADMIN_PAYROLL", "Administration payroll", "staff_cost"),
    line("OFFICE_RENT", "Office / premises rental", "occupancy"),
    line("UTILITIES", "Utilities", "utilities"),
    line("MARKETING", "Marketing & promotion", "sales_marketing"),
    line("TRANSPORT", "Transport & travel", "transport_logistics"),
    line("REPAIRS", "Repairs & maintenance", "repairs_maintenance"),
    line("OFFICE_ADMIN", "Office & administration", "administration"),
    line("PROFESSIONAL", "Professional fees", "professional_technology"),
    line("SOFTWARE", "Software & technology", "professional_technology"),
    line("DEPRECIATION", "Depreciation", "depreciation"),
    line("OTHER_OPEX", "Other operating expenses", "other_operating_expense"),
  ];
}

const templates: IndustryPnlTemplate[] = [
  {
    industry: "F&B - Restaurant / Cafe / QSR",
    revenueLines: [
      line("FOOD_SALES", "Food sales", "revenue"),
      line("BEVERAGE_SALES", "Beverage sales", "revenue"),
      line("DELIVERY_SALES", "Delivery / takeaway sales", "revenue"),
      line("CATERING_SALES", "Catering / event sales", "revenue"),
      line("OTHER_SALES", "Other operating sales", "revenue"),
    ],
    directCostLines: [
      line("FOOD_COST", "Food ingredients", "direct_cost"),
      line("BEVERAGE_COST", "Beverage ingredients", "direct_cost"),
      line("PACKAGING", "Takeaway packaging", "direct_cost"),
      line("KITCHEN_CONSUMABLES", "Kitchen consumables", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("SALARY", "Salary & wages", "staff_cost"),
      line("OT", "Overtime", "staff_cost"),
      line("EMPLOYER_CONTRIB", "Employer statutory contributions", "staff_cost"),
      line("STAFF_MEALS", "Staff meals / welfare", "staff_cost"),
      line("RENT", "Outlet rental", "occupancy"),
      line("SERVICE_CHARGE_RENT", "Mall / building service charges", "occupancy"),
      line("ELECTRIC", "Electricity", "utilities"),
      line("WATER_GAS", "Water / gas", "utilities"),
      line("DELIVERY_COMMISSION", "Delivery platform commissions", "sales_marketing"),
      line("MERCHANT_FEES", "Card / payment merchant fees", "sales_marketing"),
      line("MARKETING", "Marketing & promotion", "sales_marketing"),
      line("CLEANING", "Cleaning", "other_operating_expense"),
      line("PEST_CONTROL", "Pest control", "other_operating_expense"),
      line("LAUNDRY", "Laundry / linen", "other_operating_expense"),
      line("REPAIRS", "Equipment repairs & maintenance", "repairs_maintenance"),
      line("LICENSES", "Licences / permits", "administration"),
      line("SOFTWARE", "POS / software / technology", "professional_technology"),
      line("PROFESSIONAL", "Accounting / professional fees", "professional_technology"),
      line("DEPRECIATION", "Depreciation", "depreciation"),
    ],
    kpis: ["food cost %", "beverage cost %", "prime cost %", "labour %", "gross margin %", "operating margin %", "sales per day", "sales per labour hour", "delivery commission %"],
    supportsRestaurantTenderBreakdown: true,
  },
  {
    industry: "Bakery / Central Kitchen",
    revenueLines: [
      line("RETAIL_SALES", "Retail bakery sales", "revenue"),
      line("WHOLESALE_SALES", "Wholesale / B2B sales", "revenue"),
      line("CUSTOM_ORDER_SALES", "Custom cake / order sales", "revenue"),
      line("TRANSFER_SALES", "Internal outlet transfer value", "revenue"),
    ],
    directCostLines: [
      line("FLOUR_GRAINS", "Flour / grains", "direct_cost"),
      line("DAIRY_BUTTER", "Dairy / butter", "direct_cost"),
      line("SUGAR_CHOCOLATE", "Sugar / chocolate / fillings", "direct_cost"),
      line("OTHER_INGREDIENTS", "Other ingredients", "direct_cost"),
      line("PACKAGING", "Packaging", "direct_cost"),
      line("DIRECT_PRODUCTION_LABOUR", "Direct production labour", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("SUPERVISORY_PAYROLL", "Supervisory / admin payroll", "staff_cost"),
      line("RENT", "Bakery / kitchen rental", "occupancy"),
      line("ELECTRIC_GAS", "Production electricity / gas", "utilities"),
      line("WATER", "Water", "utilities"),
      line("DELIVERY", "Delivery / distribution", "transport_logistics"),
      line("MARKETING", "Marketing", "sales_marketing"),
      line("EQUIPMENT_REPAIR", "Oven / equipment maintenance", "repairs_maintenance"),
      line("CLEANING", "Cleaning / sanitation", "other_operating_expense"),
      line("SOFTWARE", "Software / POS", "professional_technology"),
      line("DEPRECIATION", "Equipment depreciation", "depreciation"),
    ],
    kpis: ["ingredient cost %", "production labour %", "gross margin %", "wastage %", "yield per batch", "production cost per unit", "wholesale margin %"],
  },
  {
    industry: "Retail",
    revenueLines: [
      line("RETAIL_SALES", "Retail merchandise sales", "revenue"),
      line("ONLINE_SALES", "Online / click-and-collect sales", "revenue"),
      line("OTHER_REVENUE", "Other retail revenue", "revenue"),
    ],
    directCostLines: [
      line("OPENING_STOCK", "Opening inventory", "direct_cost"),
      line("PURCHASES", "Merchandise purchases", "direct_cost"),
      line("FREIGHT_IN", "Freight-in / landed handling", "direct_cost"),
      line("CLOSING_STOCK", "Less: closing inventory", "direct_cost"),
      line("SHRINKAGE", "Stock shrinkage / write-off", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("STORE_PAYROLL", "Store payroll", "staff_cost"),
      line("COMMISSION", "Sales commission", "staff_cost"),
      line("RENT", "Store rental", "occupancy"),
      line("MALL_CHARGES", "Mall / service charges", "occupancy"),
      line("UTILITIES", "Utilities", "utilities"),
      line("MERCHANT_FEES", "Merchant / payment fees", "sales_marketing"),
      line("MARKETING", "Advertising / promotions", "sales_marketing"),
      line("DELIVERY", "Customer delivery", "transport_logistics"),
      line("REPAIRS", "Store repairs & maintenance", "repairs_maintenance"),
      line("SOFTWARE", "POS / software", "professional_technology"),
      line("DEPRECIATION", "Fixtures / equipment depreciation", "depreciation"),
    ],
    kpis: ["gross margin %", "stock turn", "inventory days", "sales per employee", "sales per sqft", "payroll %", "shrinkage %", "average transaction value"],
  },
  {
    industry: "Wholesale / Distribution",
    revenueLines: [
      line("WHOLESALE_SALES", "Wholesale sales", "revenue"),
      line("DEALER_SALES", "Dealer / reseller sales", "revenue"),
      line("DISTRIBUTION_FEES", "Distribution / handling income", "revenue"),
    ],
    directCostLines: [
      line("PRODUCT_PURCHASES", "Product purchases", "direct_cost"),
      line("FREIGHT_IN", "Freight-in", "direct_cost"),
      line("IMPORT_DUTY", "Import duties / landed charges", "direct_cost"),
      line("WAREHOUSE_HANDLING_DIRECT", "Direct warehouse handling", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("SALES_PAYROLL", "Sales payroll", "staff_cost"),
      line("SALES_COMMISSION", "Sales commission", "staff_cost"),
      line("WAREHOUSE_PAYROLL", "Warehouse payroll", "staff_cost"),
      line("WAREHOUSE_RENT", "Warehouse rental", "occupancy"),
      line("UTILITIES", "Warehouse utilities", "utilities"),
      line("OUTBOUND_DELIVERY", "Outbound transport / delivery", "transport_logistics"),
      line("VEHICLE_COST", "Vehicle running cost", "transport_logistics"),
      line("BAD_DEBTS", "Bad debts / credit losses", "other_operating_expense"),
      line("MARKETING", "Trade marketing", "sales_marketing"),
      ...standardCorporateOpex().filter((item) => !["staff_cost", "occupancy", "utilities", "sales_marketing", "transport_logistics"].includes(item.group)),
    ],
    kpis: ["gross margin %", "inventory turnover", "inventory days", "debtor days", "creditor days", "delivery cost %", "sales per salesperson"],
  },
  {
    industry: "E-commerce",
    revenueLines: [
      line("WEBSITE_SALES", "Own website sales", "revenue"),
      line("MARKETPLACE_SALES", "Marketplace sales", "revenue"),
      line("SOCIAL_COMMERCE", "Social commerce sales", "revenue"),
    ],
    directCostLines: [
      line("PRODUCT_COGS", "Product cost", "direct_cost"),
      line("PACKAGING", "Order packaging", "direct_cost"),
      line("FULFILMENT_DIRECT", "Direct fulfilment cost", "direct_cost"),
      line("RETURNS_COGS", "Returns / damaged goods", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("ECOM_PAYROLL", "E-commerce team payroll", "staff_cost"),
      line("WAREHOUSE_RENT", "Warehouse / storage", "occupancy"),
      line("MARKETPLACE_COMMISSION", "Marketplace commissions", "sales_marketing"),
      line("PAYMENT_FEES", "Payment gateway fees", "sales_marketing"),
      line("DIGITAL_ADS", "Digital advertising", "sales_marketing"),
      line("AFFILIATE", "Affiliate / influencer fees", "sales_marketing"),
      line("COURIER", "Courier / last-mile delivery", "transport_logistics"),
      line("SOFTWARE", "Store / apps / software", "professional_technology"),
      line("CUSTOMER_SERVICE", "Customer service cost", "administration"),
      line("DEPRECIATION", "Equipment depreciation", "depreciation"),
    ],
    kpis: ["contribution margin %", "gross margin %", "ad spend %", "ROAS", "fulfilment cost per order", "return rate", "average order value", "platform commission %"],
  },
  {
    industry: "Beauty / Salon / Spa",
    revenueLines: [
      line("SERVICE_REVENUE", "Hair / beauty service revenue", "revenue"),
      line("TREATMENT_REVENUE", "Treatment / package revenue", "revenue"),
      line("PRODUCT_SALES", "Retail product sales", "revenue"),
      line("MEMBERSHIP_REVENUE", "Membership / package utilisation revenue", "revenue"),
    ],
    directCostLines: [
      line("TREATMENT_CONSUMABLES", "Treatment consumables", "direct_cost"),
      line("RETAIL_COGS", "Retail product cost", "direct_cost"),
      line("DISPOSABLES", "Disposable items", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("SALARY", "Salary", "staff_cost"),
      line("SERVICE_COMMISSION", "Service commission", "staff_cost"),
      line("PRODUCT_COMMISSION", "Product commission", "staff_cost"),
      line("EMPLOYER_CONTRIB", "Employer statutory contributions", "staff_cost"),
      line("RENT", "Outlet rental", "occupancy"),
      line("UTILITIES", "Utilities", "utilities"),
      line("LAUNDRY", "Laundry / towels", "other_operating_expense"),
      line("MARKETING", "Marketing / promotion", "sales_marketing"),
      line("EQUIPMENT_REPAIR", "Equipment maintenance", "repairs_maintenance"),
      line("SOFTWARE", "Booking / POS software", "professional_technology"),
      line("DEPRECIATION", "Equipment depreciation", "depreciation"),
    ],
    kpis: ["service gross margin %", "product gross margin %", "commission %", "revenue per staff", "revenue per treatment room", "repeat customer %", "retail attachment %"],
  },
  {
    industry: "Automotive Workshop",
    revenueLines: [
      line("LABOUR_REVENUE", "Labour / service charges", "revenue"),
      line("PARTS_SALES", "Spare parts sales", "revenue"),
      line("LUBRICANT_SALES", "Lubricants / fluids sales", "revenue"),
      line("DIAGNOSTIC_FEES", "Diagnostic / inspection fees", "revenue"),
    ],
    directCostLines: [
      line("PARTS_COST", "Spare parts cost", "direct_cost"),
      line("LUBRICANTS_COST", "Lubricants / fluids cost", "direct_cost"),
      line("DIRECT_TECHNICIAN_LABOUR", "Direct technician labour", "direct_cost"),
      line("SUBLET_WORK", "Subcontract / sublet work", "direct_cost"),
      line("WORKSHOP_CONSUMABLES", "Workshop consumables", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("ADMIN_PAYROLL", "Admin / service advisor payroll", "staff_cost"),
      line("WORKSHOP_RENT", "Workshop rental", "occupancy"),
      line("UTILITIES", "Utilities", "utilities"),
      line("TOOLS_REPAIR", "Tools / equipment maintenance", "repairs_maintenance"),
      line("WASTE_DISPOSAL", "Scheduled waste / disposal", "other_operating_expense"),
      line("MARKETING", "Marketing", "sales_marketing"),
      line("VEHICLE_COST", "Workshop vehicle cost", "transport_logistics"),
      line("SOFTWARE", "Workshop software", "professional_technology"),
      line("DEPRECIATION", "Tools / equipment depreciation", "depreciation"),
    ],
    kpis: ["parts margin %", "labour gross margin %", "jobs per day", "average repair order", "technician utilisation %", "technician efficiency %", "parts-to-labour ratio"],
  },
  {
    industry: "Clinic / Dental / Healthcare",
    revenueLines: [
      line("CONSULTATION", "Consultation revenue", "revenue"),
      line("PROCEDURES", "Procedure / treatment revenue", "revenue"),
      line("MEDICINE_SALES", "Medicine / pharmacy sales", "revenue"),
      line("LAB_IMAGING", "Lab / imaging revenue", "revenue"),
      line("OTHER_CLINICAL", "Other clinical revenue", "revenue"),
    ],
    directCostLines: [
      line("MEDICINE_COST", "Medicines / drugs", "direct_cost"),
      line("MEDICAL_CONSUMABLES", "Medical consumables", "direct_cost"),
      line("LAB_FEES", "External lab / imaging fees", "direct_cost"),
      line("VISITING_PRACTITIONER", "Visiting practitioner / locum direct fees", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("CLINICAL_PAYROLL", "Clinical payroll", "staff_cost"),
      line("ADMIN_PAYROLL", "Admin payroll", "staff_cost"),
      line("RENT", "Clinic rental", "occupancy"),
      line("UTILITIES", "Utilities", "utilities"),
      line("MEDICAL_WASTE", "Clinical / scheduled waste", "other_operating_expense"),
      line("EQUIPMENT_SERVICE", "Medical equipment service", "repairs_maintenance"),
      line("LICENSE_INSURANCE", "Professional licences / insurance", "administration"),
      line("MARKETING", "Marketing", "sales_marketing"),
      line("SOFTWARE", "Clinic / EMR software", "professional_technology"),
      line("DEPRECIATION", "Medical equipment depreciation", "depreciation"),
    ],
    kpis: ["revenue per patient visit", "consumables %", "medicine margin %", "payroll %", "room / chair utilisation %", "revenue per practitioner", "procedure mix %"],
  },
  {
    industry: "Professional Services",
    revenueLines: [
      line("RETAINER_REVENUE", "Retainer revenue", "revenue"),
      line("PROJECT_FEES", "Project / engagement fees", "revenue"),
      line("HOURLY_FEES", "Hourly / billable fees", "revenue"),
      line("OTHER_FEES", "Other professional fees", "revenue"),
    ],
    directCostLines: [
      line("SUBCONTRACTORS", "Subcontractors / freelancers", "direct_cost"),
      line("DIRECT_PROJECT_LABOUR", "Direct project labour", "direct_cost"),
      line("PROJECT_DISBURSEMENTS", "Direct project disbursements", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("NON_BILLABLE_PAYROLL", "Non-billable / admin payroll", "staff_cost"),
      line("OFFICE_RENT", "Office rental", "occupancy"),
      line("SOFTWARE", "Professional software / subscriptions", "professional_technology"),
      line("PROFESSIONAL_MEMBERSHIP", "Professional memberships", "professional_technology"),
      line("PI_INSURANCE", "Professional indemnity / insurance", "administration"),
      line("BUSINESS_DEVELOPMENT", "Business development", "sales_marketing"),
      line("TRAVEL", "Client travel / transport", "transport_logistics"),
      line("ADMIN", "Office administration", "administration"),
      line("DEPRECIATION", "Office equipment depreciation", "depreciation"),
    ],
    kpis: ["revenue per professional", "billable utilisation %", "realisation rate %", "project margin %", "payroll %", "revenue per billable hour", "debtor days"],
  },
  {
    industry: "Education / Training",
    revenueLines: [
      line("TUITION_FEES", "Tuition / course fees", "revenue"),
      line("REGISTRATION_FEES", "Registration / enrolment fees", "revenue"),
      line("MATERIAL_SALES", "Learning material sales", "revenue"),
      line("CORPORATE_TRAINING", "Corporate training revenue", "revenue"),
    ],
    directCostLines: [
      line("TEACHER_DIRECT", "Direct teacher / trainer cost", "direct_cost"),
      line("COURSE_MATERIALS", "Course / learning materials", "direct_cost"),
      line("VENUE_DIRECT", "Direct external venue cost", "direct_cost"),
      line("CERTIFICATION_FEES", "Certification / examination fees", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("ADMIN_PAYROLL", "Admin payroll", "staff_cost"),
      line("CENTRE_RENT", "Centre / classroom rental", "occupancy"),
      line("UTILITIES", "Utilities", "utilities"),
      line("MARKETING", "Student acquisition / marketing", "sales_marketing"),
      line("LEARNING_SOFTWARE", "LMS / learning software", "professional_technology"),
      line("REPAIRS", "Classroom / equipment maintenance", "repairs_maintenance"),
      line("ADMIN", "Administration", "administration"),
      line("DEPRECIATION", "Equipment depreciation", "depreciation"),
    ],
    kpis: ["revenue per student", "teacher cost %", "class occupancy %", "student acquisition cost", "revenue per classroom", "course contribution margin %"],
  },
  {
    industry: "Hotel / Accommodation",
    revenueLines: [
      line("ROOM_REVENUE", "Room revenue", "revenue"),
      line("FNB_REVENUE", "Food & beverage revenue", "revenue"),
      line("EVENT_REVENUE", "Events / function revenue", "revenue"),
      line("OTHER_GUEST_REVENUE", "Other guest services", "revenue"),
    ],
    directCostLines: [
      line("ROOM_AMENITIES", "Room amenities / guest supplies", "direct_cost"),
      line("HOUSEKEEPING_CONSUMABLES", "Housekeeping consumables", "direct_cost"),
      line("LAUNDRY_DIRECT", "Direct laundry / linen", "direct_cost"),
      line("FNB_COGS", "F&B cost of sales", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("HOTEL_PAYROLL", "Hotel payroll", "staff_cost"),
      line("PROPERTY_RENT", "Property lease / occupancy", "occupancy"),
      line("ELECTRICITY", "Electricity", "utilities"),
      line("WATER_GAS", "Water / gas", "utilities"),
      line("OTA_COMMISSION", "OTA commissions", "sales_marketing"),
      line("MARKETING", "Sales & marketing", "sales_marketing"),
      line("PROPERTY_MAINTENANCE", "Property repairs & maintenance", "repairs_maintenance"),
      line("SECURITY", "Security", "other_operating_expense"),
      line("LICENSES", "Licences / assessments", "administration"),
      line("PMS_SOFTWARE", "PMS / booking software", "professional_technology"),
      line("DEPRECIATION", "FF&E depreciation", "depreciation"),
    ],
    kpis: ["occupancy %", "ADR", "RevPAR", "room gross margin %", "payroll %", "OTA commission %", "revenue per available room", "F&B margin %"],
  },
  {
    industry: "Property Rental / Management",
    revenueLines: [
      line("RENTAL_INCOME", "Rental income", "revenue"),
      line("MANAGEMENT_FEES", "Property management fees", "revenue"),
      line("SERVICE_INCOME", "Maintenance / service income", "revenue"),
      line("PARKING_OTHER", "Parking / other property income", "revenue"),
    ],
    directCostLines: [
      line("DIRECT_MAINTENANCE", "Direct property maintenance", "direct_cost"),
      line("DIRECT_CLEANING", "Direct cleaning / security", "direct_cost"),
      line("PROPERTY_UTILITIES_RECOVERABLE", "Property utilities not recovered", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("MANAGEMENT_PAYROLL", "Management / admin payroll", "staff_cost"),
      line("ASSESSMENT_QUIT_RENT", "Assessment / quit rent", "occupancy"),
      line("PROPERTY_INSURANCE", "Property insurance", "administration"),
      line("AGENT_FEES", "Leasing / agent fees", "sales_marketing"),
      line("LEGAL_PROFESSIONAL", "Legal / professional fees", "professional_technology"),
      line("ADMIN", "Property administration", "administration"),
      line("DEPRECIATION", "Property / equipment depreciation", "depreciation"),
      line("FINANCE_COST", "Property finance cost", "finance_cost"),
    ],
    kpis: ["occupancy %", "rent per unit", "collection rate %", "maintenance cost %", "NOI margin %", "arrears days", "revenue per property"],
  },
  {
    industry: "Construction / Renovation",
    revenueLines: [
      line("CONTRACT_REVENUE", "Certified / recognised contract revenue", "revenue"),
      line("VARIATION_ORDERS", "Variation orders", "revenue"),
      line("OTHER_PROJECT_REVENUE", "Other project revenue", "revenue"),
    ],
    directCostLines: [
      line("MATERIALS", "Construction materials", "direct_cost"),
      line("SITE_LABOUR", "Site labour", "direct_cost"),
      line("SUBCONTRACTORS", "Subcontractors", "direct_cost"),
      line("MACHINERY_HIRE", "Machinery / equipment hire", "direct_cost"),
      line("SITE_TRANSPORT", "Site transport / haulage", "direct_cost"),
      line("SITE_UTILITIES", "Site utilities", "direct_cost"),
      line("SITE_PRELIMINARIES", "Site preliminaries / temporary works", "direct_cost"),
      line("PROJECT_CONSULTANTS", "Direct project consultants", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("HQ_PAYROLL", "Head office payroll", "staff_cost"),
      line("OFFICE_RENT", "Head office rental", "occupancy"),
      line("VEHICLES", "Company vehicle costs", "transport_logistics"),
      line("TENDER_MARKETING", "Tender / business development", "sales_marketing"),
      line("INSURANCE", "Corporate insurance", "administration"),
      line("PROFESSIONAL", "Legal / accounting / professional", "professional_technology"),
      line("SOFTWARE", "Project / accounting software", "professional_technology"),
      line("DEPRECIATION", "Plant / equipment depreciation", "depreciation"),
      line("FINANCE_COST", "Finance cost", "finance_cost"),
    ],
    kpis: ["project gross margin %", "material %", "site labour %", "subcontractor %", "project variance", "WIP", "retention receivable", "debtor days", "backlog value"],
  },
  {
    industry: "Manufacturing",
    revenueLines: [
      line("FINISHED_GOODS", "Finished goods sales", "revenue"),
      line("CONTRACT_MANUFACTURING", "Contract manufacturing revenue", "revenue"),
      line("SCRAP_BYPRODUCT", "Scrap / by-product income", "revenue"),
    ],
    directCostLines: [
      line("RAW_MATERIALS", "Raw materials consumed", "direct_cost"),
      line("DIRECT_LABOUR", "Direct labour", "direct_cost"),
      line("FACTORY_UTILITIES", "Factory electricity / gas / water", "direct_cost"),
      line("PRODUCTION_CONSUMABLES", "Production consumables", "direct_cost"),
      line("PACKAGING", "Production packaging", "direct_cost"),
      line("FACTORY_MAINTENANCE", "Factory maintenance", "direct_cost"),
      line("FACTORY_DEPRECIATION", "Production equipment depreciation", "direct_cost"),
      line("OTHER_FACTORY_OVERHEAD", "Other factory overhead", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("ADMIN_PAYROLL", "Administration payroll", "staff_cost"),
      line("SALES_PAYROLL", "Sales payroll / commission", "staff_cost"),
      line("OFFICE_RENT", "Office / non-factory occupancy", "occupancy"),
      line("OUTBOUND_FREIGHT", "Outbound freight / distribution", "transport_logistics"),
      line("MARKETING", "Marketing", "sales_marketing"),
      line("QUALITY_COMPLIANCE", "Quality / compliance", "administration"),
      line("SOFTWARE", "ERP / software", "professional_technology"),
      line("PROFESSIONAL", "Professional fees", "professional_technology"),
      line("ADMIN_DEPRECIATION", "Non-production depreciation", "depreciation"),
      line("FINANCE_COST", "Finance cost", "finance_cost"),
    ],
    kpis: ["material cost %", "direct labour per unit", "factory overhead %", "yield %", "scrap %", "gross profit per unit", "capacity utilisation %", "OEE", "inventory days"],
  },
  {
    industry: "Logistics / Transport",
    revenueLines: [
      line("TRANSPORT_REVENUE", "Transport / delivery revenue", "revenue"),
      line("CONTRACT_REVENUE", "Contract logistics revenue", "revenue"),
      line("SURCHARGE_INCOME", "Fuel / toll surcharges", "revenue"),
      line("WAREHOUSE_SERVICE", "Warehousing / handling revenue", "revenue"),
    ],
    directCostLines: [
      line("DRIVER_DIRECT", "Driver direct wages", "direct_cost"),
      line("FUEL", "Fuel", "direct_cost"),
      line("TOLLS", "Tolls / parking", "direct_cost"),
      line("SUBCONTRACT_TRANSPORT", "Subcontract transport", "direct_cost"),
      line("TRIP_ALLOWANCE", "Trip allowances", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("OPS_PAYROLL", "Operations / admin payroll", "staff_cost"),
      line("DEPOT_RENT", "Depot / warehouse rental", "occupancy"),
      line("VEHICLE_REPAIR", "Vehicle repairs & tyres", "repairs_maintenance"),
      line("ROAD_TAX_INSURANCE", "Road tax / vehicle insurance", "administration"),
      line("GPS_SOFTWARE", "Fleet GPS / software", "professional_technology"),
      line("MARKETING", "Sales & marketing", "sales_marketing"),
      line("VEHICLE_DEPRECIATION", "Vehicle depreciation", "depreciation"),
      line("FINANCE_COST", "Hire purchase / finance cost", "finance_cost"),
    ],
    kpis: ["revenue per vehicle", "fuel %", "fuel cost per km", "cost per km", "revenue per km", "fleet utilisation %", "vehicle downtime %", "gross margin per trip"],
  },
  {
    industry: "Agriculture / Aquaculture",
    revenueLines: [
      line("CROP_SALES", "Crop / produce sales", "revenue"),
      line("LIVESTOCK_SALES", "Livestock sales", "revenue"),
      line("AQUACULTURE_SALES", "Aquaculture sales", "revenue"),
      line("OTHER_FARM_INCOME", "Other farm income", "revenue"),
    ],
    directCostLines: [
      line("SEED_STOCK", "Seeds / fingerlings / stock", "direct_cost"),
      line("FEED", "Feed", "direct_cost"),
      line("FERTILISER", "Fertiliser / nutrients", "direct_cost"),
      line("FARM_INPUTS", "Crop protection / farm inputs", "direct_cost"),
      line("DIRECT_FARM_LABOUR", "Direct farm labour", "direct_cost"),
      line("HARVEST_PACKING", "Harvest / packing", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("SUPERVISORY_PAYROLL", "Supervisory / admin payroll", "staff_cost"),
      line("LAND_RENT", "Land / farm rental", "occupancy"),
      line("FARM_UTILITIES", "Farm electricity / water", "utilities"),
      line("MACHINERY_FUEL", "Machinery fuel", "transport_logistics"),
      line("MACHINERY_REPAIR", "Machinery / irrigation maintenance", "repairs_maintenance"),
      line("VET_TESTING", "Veterinary / testing", "professional_technology"),
      line("TRANSPORT", "Produce transport", "transport_logistics"),
      line("DEPRECIATION", "Farm equipment depreciation", "depreciation"),
    ],
    kpis: ["yield per acre / pond", "feed cost %", "feed conversion ratio", "mortality %", "direct labour %", "cost per kg / unit", "wastage %", "gross margin per crop / batch"],
  },
  {
    industry: "Trading / Import Export",
    revenueLines: [
      line("LOCAL_SALES", "Local trading sales", "revenue"),
      line("EXPORT_SALES", "Export sales", "revenue"),
      line("COMMISSION_INCOME", "Trading / sourcing commission", "revenue"),
    ],
    directCostLines: [
      line("PURCHASE_COST", "Goods purchased", "direct_cost"),
      line("FREIGHT_IN", "International freight-in", "direct_cost"),
      line("DUTY_CLEARANCE", "Duties / customs / clearance", "direct_cost"),
      line("MARINE_INSURANCE", "Cargo insurance", "direct_cost"),
      line("LANDING_HANDLING", "Port / landed handling", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("TRADING_PAYROLL", "Trading / sales payroll", "staff_cost"),
      line("WAREHOUSE_RENT", "Warehouse rental", "occupancy"),
      line("OUTBOUND_FREIGHT", "Outbound freight", "transport_logistics"),
      line("BANK_TRADE_FEES", "Trade finance / bank charges", "finance_cost"),
      line("FOREX_GAIN_LOSS", "Foreign exchange gain / loss", "other_non_operating"),
      line("MARKETING", "Sales & marketing", "sales_marketing"),
      line("PROFESSIONAL", "Customs / professional fees", "professional_technology"),
      line("ADMIN", "Administration", "administration"),
    ],
    kpis: ["landed margin %", "gross margin %", "inventory turn", "debtor days", "FX impact %", "freight %", "margin by SKU / shipment"],
  },
  {
    industry: "Technology / SaaS",
    revenueLines: [
      line("SUBSCRIPTION_REVENUE", "Subscription revenue", "revenue"),
      line("SETUP_FEES", "Setup / implementation fees", "revenue"),
      line("SERVICES_REVENUE", "Development / professional services", "revenue"),
      line("USAGE_REVENUE", "Usage / transaction revenue", "revenue"),
    ],
    directCostLines: [
      line("HOSTING_COGS", "Hosting / cloud directly attributable", "direct_cost"),
      line("API_COGS", "Third-party APIs / infrastructure", "direct_cost"),
      line("PAYMENT_PROCESSING", "Payment processing", "direct_cost"),
      line("SUPPORT_DIRECT", "Direct customer support cost", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("ENGINEERING_PAYROLL", "Engineering / product payroll", "staff_cost"),
      line("SALES_PAYROLL", "Sales payroll / commission", "staff_cost"),
      line("GNA_PAYROLL", "G&A payroll", "staff_cost"),
      line("OFFICE", "Office / co-working", "occupancy"),
      line("SALES_MARKETING", "Sales & marketing", "sales_marketing"),
      line("SOFTWARE_TOOLS", "Internal software / tools", "professional_technology"),
      line("PROFESSIONAL", "Legal / accounting / professional", "professional_technology"),
      line("TRAVEL", "Travel", "transport_logistics"),
      line("DEPRECIATION", "Equipment depreciation", "depreciation"),
    ],
    kpis: ["MRR", "ARR", "gross margin %", "net revenue retention %", "logo churn %", "CAC", "CAC payback months", "ARPU", "LTV", "burn multiple"],
  },
  {
    industry: "Agency / Events",
    revenueLines: [
      line("RETAINER_REVENUE", "Retainer revenue", "revenue"),
      line("PROJECT_REVENUE", "Campaign / project revenue", "revenue"),
      line("EVENT_REVENUE", "Event production revenue", "revenue"),
      line("MEDIA_SERVICE_FEES", "Media / management fees", "revenue"),
    ],
    directCostLines: [
      line("FREELANCERS", "Freelancers / creative contractors", "direct_cost"),
      line("PRODUCTION", "Production / fabrication", "direct_cost"),
      line("PRINTING", "Printing / materials", "direct_cost"),
      line("VENUE", "Venue / event direct cost", "direct_cost"),
      line("TALENT", "Talent / entertainment", "direct_cost"),
      line("MEDIA_PASS_THROUGH", "Client media spend / pass-through", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("TEAM_PAYROLL", "Core team payroll", "staff_cost"),
      line("OFFICE_RENT", "Office rental", "occupancy"),
      line("SOFTWARE", "Creative / project software", "professional_technology"),
      line("BUSINESS_DEV", "Business development", "sales_marketing"),
      line("TRAVEL", "Travel / transport", "transport_logistics"),
      line("ADMIN", "Administration", "administration"),
      line("PROFESSIONAL", "Professional fees", "professional_technology"),
      line("DEPRECIATION", "Equipment depreciation", "depreciation"),
    ],
    kpis: ["project gross margin %", "revenue per staff", "freelancer %", "billable utilisation %", "retainer mix %", "client concentration %", "project overrun %"],
  },
  {
    industry: "Cleaning / Security / Manpower",
    revenueLines: [
      line("CONTRACT_REVENUE", "Monthly contract revenue", "revenue"),
      line("ADHOC_REVENUE", "Ad-hoc job revenue", "revenue"),
      line("MANPOWER_REVENUE", "Manpower / deployment charges", "revenue"),
    ],
    directCostLines: [
      line("FRONTLINE_WAGES", "Frontline worker wages", "direct_cost"),
      line("FRONTLINE_OT", "Frontline overtime", "direct_cost"),
      line("FRONTLINE_STATUTORY", "Frontline statutory contributions", "direct_cost"),
      line("UNIFORMS", "Uniforms / PPE", "direct_cost"),
      line("DIRECT_SUPPLIES", "Direct cleaning / operating supplies", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("SUPERVISOR_PAYROLL", "Supervisor / admin payroll", "staff_cost"),
      line("RECRUITMENT", "Recruitment / onboarding", "staff_cost"),
      line("OFFICE_RENT", "Office / store rental", "occupancy"),
      line("STAFF_TRANSPORT", "Worker transport", "transport_logistics"),
      line("VEHICLE_COST", "Vehicle cost", "transport_logistics"),
      line("TRAINING", "Training", "administration"),
      line("LICENSES", "Licences / compliance", "administration"),
      line("SOFTWARE", "Scheduling / payroll software", "professional_technology"),
      line("ADMIN", "Administration", "administration"),
    ],
    kpis: ["direct labour %", "contract gross margin %", "revenue per worker", "OT %", "worker utilisation %", "turnover %", "recruitment cost per worker", "supervisor span"],
  },
  {
    industry: "Engineering / Maintenance",
    revenueLines: [
      line("SERVICE_CALLS", "Service call revenue", "revenue"),
      line("MAINTENANCE_CONTRACT", "Maintenance contract revenue", "revenue"),
      line("INSTALLATION", "Installation / project revenue", "revenue"),
      line("PARTS_SALES", "Parts / components sales", "revenue"),
    ],
    directCostLines: [
      line("PARTS_COST", "Parts / components", "direct_cost"),
      line("DIRECT_TECHNICIAN", "Direct technician labour", "direct_cost"),
      line("SUBCONTRACTORS", "Subcontractors", "direct_cost"),
      line("PROJECT_MATERIALS", "Project materials", "direct_cost"),
      line("DIRECT_TRAVEL", "Direct job travel", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("ADMIN_PAYROLL", "Admin / supervisor payroll", "staff_cost"),
      line("WORKSHOP_RENT", "Workshop / office rental", "occupancy"),
      line("VEHICLES", "Service vehicles", "transport_logistics"),
      line("TOOLS_REPAIR", "Tools / equipment maintenance", "repairs_maintenance"),
      line("CERTIFICATION", "Certification / training", "administration"),
      line("SOFTWARE", "Service management software", "professional_technology"),
      line("MARKETING", "Sales & marketing", "sales_marketing"),
      line("DEPRECIATION", "Tools / vehicle depreciation", "depreciation"),
    ],
    kpis: ["job gross margin %", "technician utilisation %", "first-time fix %", "callback rate", "revenue per technician", "parts margin %", "contract renewal %"],
  },
  {
    industry: "Mining / Quarry / Materials",
    revenueLines: [
      line("MATERIAL_SALES", "Aggregate / material sales", "revenue"),
      line("DELIVERY_REVENUE", "Haulage / delivery revenue", "revenue"),
      line("OTHER_QUARRY_REVENUE", "Other quarry revenue", "revenue"),
    ],
    directCostLines: [
      line("EXTRACTION_LABOUR", "Extraction / production labour", "direct_cost"),
      line("FUEL_DIRECT", "Production diesel / fuel", "direct_cost"),
      line("PLANT_OPERATING", "Plant operating cost", "direct_cost"),
      line("PRODUCTION_CONSUMABLES", "Production consumables", "direct_cost"),
      line("ROYALTY_DIRECT", "Royalties / extraction-linked charges", "direct_cost"),
      line("CRUSHING_SCREENING", "Crushing / screening cost", "direct_cost"),
    ],
    operatingExpenseLines: [
      line("ADMIN_PAYROLL", "Admin / management payroll", "staff_cost"),
      line("SITE_RENT", "Land / site occupancy", "occupancy"),
      line("HEAVY_MAINTENANCE", "Heavy equipment maintenance", "repairs_maintenance"),
      line("HAULAGE", "Outbound haulage", "transport_logistics"),
      line("LICENSE_COMPLIANCE", "Licences / environmental compliance", "administration"),
      line("LAB_TESTING", "Testing / professional fees", "professional_technology"),
      line("PLANT_DEPRECIATION", "Plant / equipment depreciation", "depreciation"),
      line("FINANCE_COST", "Equipment finance cost", "finance_cost"),
    ],
    kpis: ["cost per tonne", "revenue per tonne", "gross profit per tonne", "production tonnes", "plant utilisation %", "fuel per tonne", "downtime %", "haulage %"],
  },
  {
    industry: "Other SME",
    revenueLines: [
      line("CORE_REVENUE", "Core operating revenue", "revenue"),
      line("OTHER_REVENUE", "Other operating revenue", "revenue"),
    ],
    directCostLines: [
      line("DIRECT_MATERIAL", "Direct material / purchases", "direct_cost"),
      line("DIRECT_LABOUR", "Direct labour", "direct_cost"),
      line("OTHER_DIRECT", "Other direct cost", "direct_cost"),
    ],
    operatingExpenseLines: standardCorporateOpex(),
    kpis: ["gross margin %", "labour %", "operating margin %", "revenue per employee", "cash conversion", "debtor days"],
  },
];

export const INDUSTRY_PNL_TEMPLATES: Record<ManagedAccountIndustry, IndustryPnlTemplate> = Object.fromEntries(
  templates.map((template) => [template.industry, template]),
) as Record<ManagedAccountIndustry, IndustryPnlTemplate>;

export function getIndustryPnlTemplate(industry: ManagedAccountIndustry) {
  return INDUSTRY_PNL_TEMPLATES[industry];
}

export function listIndustryPnlTemplates() {
  return templates;
}
