"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { smartPosRequest } from "./lib/api";

type Vertical="beauty"|"pet";
type Pet={id:string;name:string;breed:string;species:string};
type Customer={id:string;name:string;telephone:string;email?:string;pets:Pet[];totalSpend:number;visitCount:number};
type Service={id:string;name:string;category:string;durationMinutes:number;price:number};
type Product={id:string;sku:string;name:string;inventoryType:"retail"|"backbar";salePrice:number;stockQuantity:number;reorderLevel:number};
const money=(value:number)=>new Intl.NumberFormat("en-MY",{style:"currency",currency:"MYR"}).format(value||0);
const input="mt-1 w-full rounded-xl border border-[#20282c]/15 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#5e8983]";

export function CustomersPanel({vertical}:{vertical:Vertical}){const [customers,setCustomers]=useState<Customer[]>([]);const [adding,setAdding]=useState(false);const [error,setError]=useState("");const load=()=>smartPosRequest<{customers:Customer[]}>("/api/smartpos/customers").then(r=>setCustomers(r.customers)).catch(e=>setError(e.message));useEffect(()=>{load()},[]);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const f=new FormData(event.currentTarget);try{await smartPosRequest("/api/smartpos/customers",{method:"POST",body:JSON.stringify({name:f.get("name"),telephone:f.get("telephone"),email:f.get("email"),notes:f.get("notes"),pets:vertical==="pet"?[{name:f.get("petName"),breed:f.get("breed"),species:f.get("species")}]:[]})});setAdding(false);load();}catch(e){setError(e instanceof Error?e.message:"Could not add customer.");}}
return <Panel title={vertical==="pet"?"Owners & Pets":"Clients"} action={<button onClick={()=>setAdding(!adding)} className={primary}>＋ {vertical==="pet"?"Add Owner & Pet":"Add Client"}</button>}>{error&&<ErrorBox text={error}/>} {adding&&<form onSubmit={submit} className="mb-6 grid gap-3 rounded-2xl bg-[#f8f6f1] p-5 sm:grid-cols-2"><Field name="name" label={vertical==="pet"?"Owner name":"Client name"}/><Field name="telephone" label="Telephone number"/><Field name="email" label="Email (optional)" type="email" required={false}/>{vertical==="pet"&&<><Field name="petName" label="Pet name"/><Field name="breed" label="Breed"/><label className="text-sm font-semibold">Species<select name="species" className={input}><option value="dog">Dog</option><option value="cat">Cat</option><option value="other">Other</option></select></label></>}<label className="text-sm font-semibold sm:col-span-2">Notes<textarea name="notes" rows={2} className={input}/></label><button className={`${primary} sm:col-span-2`}>Save {vertical==="pet"?"Owner & Pet":"Client"}</button></form>} {customers.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs text-[#6d777a]"><tr><th className="p-3">{vertical==="pet"?"Owner":"Client"}</th>{vertical==="pet"&&<th className="p-3">Pets</th>}<th className="p-3">Telephone</th><th className="p-3">Visits</th><th className="p-3">Total spend</th></tr></thead><tbody>{customers.map(c=><tr key={c.id} className="border-b border-[#20282c]/8"><td className="p-3 font-semibold">{c.name}</td>{vertical==="pet"&&<td className="p-3">{c.pets.map(p=>`${p.name} · ${p.breed}`).join(", ")}</td>}<td className="p-3">{c.telephone}</td><td className="p-3">{c.visitCount}</td><td className="p-3 font-bold">{money(c.totalSpend)}</td></tr>)}</tbody></table></div>:<Empty text={vertical==="pet"?"No owners or pets yet.":"No clients yet."}/>}</Panel>}

export function InventoryPanel(){const [products,setProducts]=useState<Product[]>([]);const [services,setServices]=useState<Service[]>([]);const [mode,setMode]=useState<"product"|"service">("product");const [adding,setAdding]=useState(false);const [error,setError]=useState("");const load=()=>Promise.all([smartPosRequest<{products:Product[]}>("/api/smartpos/products"),smartPosRequest<{services:Service[]}>("/api/smartpos/services")]).then(([p,s])=>{setProducts(p.products);setServices(s.services)}).catch(e=>setError(e.message));useEffect(()=>{load()},[]);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{if(mode==="product")await smartPosRequest("/api/smartpos/products",{method:"POST",body:JSON.stringify({sku:f.get("sku"),name:f.get("name"),inventoryType:f.get("inventoryType"),salePrice:Number(f.get("price")),stockQuantity:Number(f.get("stock")),reorderLevel:Number(f.get("reorder"))})});else await smartPosRequest("/api/smartpos/services",{method:"POST",body:JSON.stringify({name:f.get("name"),category:f.get("category"),durationMinutes:Number(f.get("duration")),price:Number(f.get("price"))})});setAdding(false);load();}catch(e){setError(e instanceof Error?e.message:"Could not save item.");}}
return <Panel title="Products & Services" action={<button onClick={()=>setAdding(!adding)} className={primary}>＋ Add Item</button>}>{error&&<ErrorBox text={error}/>}<div className="mb-5 flex gap-2"><Tab active={mode==="product"} onClick={()=>setMode("product")} text="Products & Stock"/><Tab active={mode==="service"} onClick={()=>setMode("service")} text="Services"/></div>{adding&&<form onSubmit={submit} className="mb-6 grid gap-3 rounded-2xl bg-[#f8f6f1] p-5 sm:grid-cols-2">{mode==="product"&&<Field name="sku" label="SKU"/>}<Field name="name" label={mode==="product"?"Product name":"Service name"}/>{mode==="product"?<><label className="text-sm font-semibold">Inventory type<select name="inventoryType" className={input}><option value="retail">Retail product</option><option value="backbar">Backbar consumable</option></select></label><Field name="stock" label="Opening stock" type="number"/><Field name="reorder" label="Low-stock warning" type="number"/></>:<><Field name="category" label="Category"/><Field name="duration" label="Duration (minutes)" type="number"/></>}<Field name="price" label={mode==="product"?"Selling price (RM)":"Service price (RM)"} type="number" step="0.01"/><button className={`${primary} sm:col-span-2`}>Save {mode}</button></form>}{mode==="product"?(products.length?<div className="grid gap-3 md:grid-cols-2">{products.map(p=><div key={p.id} className="rounded-xl border border-[#20282c]/10 p-4"><div className="flex justify-between"><div><b>{p.name}</b><p className="mt-1 text-xs text-[#6d777a]">{p.sku} · {p.inventoryType}</p></div><b>{money(p.salePrice)}</b></div><p className={`mt-4 text-sm font-semibold ${p.stockQuantity<=p.reorderLevel?"text-red-600":"text-[#497973]"}`}>{p.stockQuantity} in stock{p.stockQuantity<=p.reorderLevel?" · Low stock":""}</p></div>)}</div>:<Empty text="No products yet. Add your first retail or backbar product."/>):(services.length?<div className="grid gap-3 md:grid-cols-2">{services.map(s=><div key={s.id} className="flex items-center justify-between rounded-xl border border-[#20282c]/10 p-4"><div><b>{s.name}</b><p className="mt-1 text-xs text-[#6d777a]">{s.category} · {s.durationMinutes} minutes</p></div><b>{money(s.price)}</b></div>)}</div>:<Empty text="No services yet. Add a service before creating appointments."/>)}</Panel>}

export function PosPanel(){const [customers,setCustomers]=useState<Customer[]>([]);const [services,setServices]=useState<Service[]>([]);const [products,setProducts]=useState<Product[]>([]);const [customerId,setCustomerId]=useState("");const [cart,setCart]=useState<{itemType:"service"|"product";itemId:string;name:string;price:number;quantity:number}[]>([]);const [payment,setPayment]=useState("cash");const [message,setMessage]=useState("");useEffect(()=>{Promise.all([smartPosRequest<{customers:Customer[]}>("/api/smartpos/customers"),smartPosRequest<{services:Service[]}>("/api/smartpos/services"),smartPosRequest<{products:Product[]}>("/api/smartpos/products")]).then(([c,s,p])=>{setCustomers(c.customers);setServices(s.services);setProducts(p.products.filter(x=>x.inventoryType==="retail"&&x.stockQuantity>0));}).catch(e=>setMessage(e.message));},[]);const total=useMemo(()=>cart.reduce((sum,i)=>sum+i.price*i.quantity,0),[cart]);function add(itemType:"service"|"product",item:Service|Product){const price="price" in item?item.price:item.salePrice;setCart(current=>{const found=current.find(x=>x.itemType===itemType&&x.itemId===item.id);return found?current.map(x=>x===found?{...x,quantity:x.quantity+1}:x):[...current,{itemType,itemId:item.id,name:item.name,price,quantity:1}]})}async function checkout(){setMessage("");try{if(!customerId)throw new Error("Choose a customer first.");await smartPosRequest("/api/smartpos/sales",{method:"POST",body:JSON.stringify({customerId,paymentMethod:payment,lines:cart.map(({itemType,itemId,quantity})=>({itemType,itemId,quantity}))})});setCart([]);setMessage("Payment recorded successfully.");}catch(e){setMessage(e instanceof Error?e.message:"Checkout failed.");}}
return <Panel title="Point of Sale"><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section><label className="text-sm font-semibold">Customer<select value={customerId} onChange={e=>setCustomerId(e.target.value)} className={input}><option value="">Choose customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><h3 className="mt-6 font-bold">Services</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{services.map(s=><button key={s.id} onClick={()=>add("service",s)} className="flex justify-between rounded-xl border border-[#20282c]/10 p-3 text-left hover:bg-[#f8f6f1]"><span>{s.name}</span><b>{money(s.price)}</b></button>)}</div><h3 className="mt-6 font-bold">Retail products</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{products.map(p=><button key={p.id} onClick={()=>add("product",p)} className="flex justify-between rounded-xl border border-[#20282c]/10 p-3 text-left hover:bg-[#f8f6f1]"><span>{p.name}</span><b>{money(p.salePrice)}</b></button>)}</div>{!services.length&&!products.length&&<Empty text="Add services or retail products in Products & Services first."/>}</section><aside className="rounded-2xl bg-[#132126] p-5 text-white"><h3 className="font-bold">Current sale</h3><div className="mt-4 min-h-36 space-y-3">{cart.map((item,index)=><div key={`${item.itemType}-${item.itemId}`} className="flex justify-between text-sm"><span>{item.quantity} × {item.name}</span><span>{money(item.price*item.quantity)} <button onClick={()=>setCart(c=>c.filter((_,i)=>i!==index))} className="ml-2 text-white/40">×</button></span></div>)}{!cart.length&&<p className="text-sm text-white/40">Select a service or product.</p>}</div><div className="border-t border-white/10 pt-4"><div className="flex justify-between text-xl font-bold"><span>Total</span><span>{money(total)}</span></div><select value={payment} onChange={e=>setPayment(e.target.value)} className="mt-4 w-full rounded-xl bg-white/10 p-3 text-sm"><option className="text-black" value="cash">Cash</option><option className="text-black" value="card">Card</option><option className="text-black" value="duitnow">DuitNow</option></select><button disabled={!cart.length} onClick={checkout} className="mt-3 w-full rounded-xl bg-[#d2aa62] p-3 font-bold text-[#132126] disabled:opacity-40">Complete Payment</button>{message&&<p className="mt-3 text-xs text-[#f1dfbc]">{message}</p>}</div></aside></div></Panel>}

export function InsightsPanel(){const [data,setData]=useState<{summary:{customerCount:number;totalRevenue:number;averageSpend:number};customers:{id:string;name:string;totalSpend:number;visitCount:number;lastVisitAt?:string}[]}|null>(null);const [error,setError]=useState("");useEffect(()=>{smartPosRequest<typeof data>("/api/smartpos/insights").then(setData).catch(e=>setError(e.message))},[]);return <Panel title="Customer Insights">{error&&<ErrorBox text={error}/>}<div className="grid gap-3 sm:grid-cols-3"><Stat label="Customers" value={String(data?.summary.customerCount||0)}/><Stat label="Total sales" value={money(data?.summary.totalRevenue||0)}/><Stat label="Average spend" value={money(data?.summary.averageSpend||0)}/></div><h3 className="mt-7 font-bold">Top customers by spending</h3>{data?.customers.length?<div className="mt-3 space-y-2">{data.customers.map((c,index)=><div key={c.id} className="flex items-center justify-between rounded-xl border border-[#20282c]/10 p-4"><span><b>{index+1}. {c.name}</b><small className="ml-3 text-[#6d777a]">{c.visitCount} visits</small></span><b>{money(c.totalSpend)}</b></div>)}</div>:<Empty text="Insights will appear after your first completed sale."/>}</Panel>}

export function NewAppointmentForm({vertical,onDone,onCancel}:{vertical:Vertical;onDone:()=>void;onCancel:()=>void}){const [customers,setCustomers]=useState<Customer[]>([]);const [services,setServices]=useState<Service[]>([]);const [customerId,setCustomerId]=useState("");const [error,setError]=useState("");useEffect(()=>{Promise.all([smartPosRequest<{customers:Customer[]}>("/api/smartpos/customers"),smartPosRequest<{services:Service[]}>("/api/smartpos/services")]).then(([c,s])=>{setCustomers(c.customers);setServices(s.services)}).catch(e=>setError(e.message))},[]);const selected=customers.find(c=>c.id===customerId);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await smartPosRequest("/api/smartpos/appointments",{method:"POST",body:JSON.stringify({customerId,petId:f.get("petId"),serviceId:f.get("serviceId"),staffName:f.get("staffName"),startAt:f.get("startAt")})});onDone();}catch(e){setError(e instanceof Error?e.message:"Could not create appointment.");}}return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-[24px] bg-[#f8f6f1] p-6 shadow-2xl"><div className="flex justify-between"><h2 className="font-serif text-3xl">New Appointment</h2><button type="button" onClick={onCancel}>✕</button></div>{error&&<ErrorBox text={error}/>}<div className="mt-5 grid gap-3"><label className="text-sm font-semibold">{vertical==="pet"?"Owner":"Client"}<select required value={customerId} onChange={e=>setCustomerId(e.target.value)} className={input}><option value="">Choose</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>{vertical==="pet"&&<label className="text-sm font-semibold">Pet<select required name="petId" className={input}><option value="">Choose pet</option>{selected?.pets.map(p=><option value={p.id} key={p.id}>{p.name} · {p.breed}</option>)}</select></label>}<label className="text-sm font-semibold">Service<select required name="serviceId" className={input}><option value="">Choose service</option>{services.map(s=><option value={s.id} key={s.id}>{s.name} · {money(s.price)}</option>)}</select></label><Field name="staffName" label={vertical==="pet"?"Groomer name":"Staff name"}/><Field name="startAt" label="Date and time" type="datetime-local"/><button className={primary}>Save Appointment</button></div>{(!customers.length||!services.length)&&<p className="mt-4 text-xs text-[#8b5f35]">Add a customer and service before creating an appointment.</p>}</form></div>}

function Panel({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <div className="rounded-2xl border border-[#20282c]/10 bg-white p-5 shadow-sm sm:p-7"><div className="mb-6 flex items-center justify-between"><h2 className="font-serif text-3xl">{title}</h2>{action}</div>{children}</div>}
function Field({label,required=true,...props}:{label:string;required?:boolean}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="text-sm font-semibold">{label}<input required={required} {...props} className={input}/></label>}
function Empty({text}:{text:string}){return <div className="my-5 rounded-xl border border-dashed border-[#20282c]/15 p-8 text-center text-sm text-[#6d777a]">{text}</div>}
function ErrorBox({text}:{text:string}){return <p className="my-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{text}</p>}
function Tab({active,onClick,text}:{active:boolean;onClick:()=>void;text:string}){return <button onClick={onClick} className={`rounded-full px-4 py-2 text-sm font-bold ${active?"bg-[#20282c] text-white":"border border-[#20282c]/10"}`}>{text}</button>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#f8f6f1] p-4"><p className="text-xs text-[#6d777a]">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>}
const primary="rounded-xl bg-[#20282c] px-4 py-3 text-sm font-bold text-white disabled:opacity-40";
