"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { AuthShell } from "../signup/page";
import { smartPosRequest } from "../lib/api";

const inputClass="mt-2 w-full rounded-xl border border-[#20282c]/15 bg-[#fbfaf7] px-4 py-3 outline-none focus:border-[#5e8983]";
export default function ForgotPassword(){const[step,setStep]=useState<"email"|"code"|"password"|"done">("email");const[challengeId,setChallengeId]=useState("");const[token,setToken]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function run<T>(path:string,body:unknown){setBusy(true);setError("");try{return await smartPosRequest<T>(path,{method:"POST",body:JSON.stringify(body)});}catch(e){setError(e instanceof Error?e.message:"Request failed.");return null;}finally{setBusy(false);}}
return <AuthShell title="Reset Your Password" text="Use your verified business email to create a new password.">{step==="email"&&<form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await run<{challengeId:string}>("/api/smartpos/auth/password/start",{email:f.get("email")});if(r?.challengeId){setChallengeId(r.challengeId);setStep("code");}}} className="space-y-4"><Field name="email" label="Email address" type="email"/><Action busy={busy} label="Send Verification Code"/></form>}{step==="code"&&<form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await run<{verificationToken:string}>("/api/smartpos/auth/password/verify",{challengeId,code:f.get("code")});if(r?.verificationToken){setToken(r.verificationToken);setStep("password");}}} className="space-y-4"><Field name="code" label="Verification code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6}/><Action busy={busy} label="Verify Code"/></form>}{step==="password"&&<form onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("password")!==f.get("confirm")){setError("Passwords do not match.");return;}const r=await run("/api/smartpos/auth/password/complete",{challengeId,verificationToken:token,password:f.get("password")});if(r)setStep("done");}} className="space-y-4"><Field name="password" label="New password" type="password" minLength={8}/><Field name="confirm" label="Confirm password" type="password" minLength={8}/><Action busy={busy} label="Change Password"/></form>}{step==="done"&&<div className="text-center"><p className="rounded-xl bg-[#5e8983]/10 p-4 text-[#35645e]">Your password has been changed.</p><Link href="/wedge-smartpos/login" className="mt-5 inline-block font-bold text-[#497973]">Return to Merchant Login</Link></div>}{error&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}</AuthShell>;}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string;name:string}){const{label,...input}=props;return <label className="block text-sm font-semibold">{label}<input {...input} required className={inputClass}/></label>;}
function Action({busy,label}:{busy:boolean;label:string}){return <button disabled={busy} className="w-full rounded-xl bg-[#20282c] px-5 py-4 font-bold text-white disabled:opacity-60">{busy?"Please wait...":label}</button>;}
