"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import {
  productConfig,
  productRequest,
  saveProductToken,
  type PaidProduct,
  type ProductSubscription,
} from "../lib/productAccess";

const inputClass = "mt-2 w-full rounded-xl border border-[#20282c]/15 bg-[#fbfaf7] px-4 py-3 outline-none focus:border-[#5e8983]";

function Shell({ product, title, text, children }: { product: PaidProduct; title: string; text: string; children: React.ReactNode }) {
  const config = productConfig[product];
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,rgba(210,170,98,.18),transparent_30%),#f3efe7] px-5 py-10 text-[#20282c]"><div className="mx-auto max-w-lg"><a href={config.basePath} className="mb-8 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#20282c] font-black text-[#f1dfbc]">W</span><b>{config.name}</b></a><section className="rounded-[28px] border border-[#20282c]/10 bg-white p-6 shadow-[0_24px_70px_rgba(32,40,44,.12)] sm:p-9"><p className="text-xs font-bold tracking-[.22em] text-[#b08745]">{config.eyebrow}</p><h1 className="mt-3 font-serif text-4xl">{title}</h1><p className="mt-3 text-sm leading-6 text-[#657074]">{text}</p><div className="mt-7">{children}</div></section></div></main>;
}

function Field(props: React.InputHTMLAttributes<HTMLInputElement> & { label: string; name: string }) {
  const { label, ...input } = props;
  return <label className="block text-sm font-semibold">{label}<input {...input} required className={inputClass} /></label>;
}

export function ProductSignupPage({ product }: { product: PaidProduct }) {
  const router = useRouter(); const config = productConfig[product];
  const [step, setStep] = useState<"details" | "code" | "password">("details");
  const [challengeId, setChallengeId] = useState(""); const [verificationToken, setVerificationToken] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submitDetails(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); try { const result = await productRequest<{challengeId:string}>(product,"/api/saas/auth/signup/start",{method:"POST",body:JSON.stringify({product,ownerName:form.get("ownerName"),businessName:form.get("businessName"),email:form.get("email"),telephone:form.get("telephone"),businessAddress:form.get("businessAddress"),acceptedTerms:form.get("acceptedTerms")==="on"})},false); setChallengeId(result.challengeId); setStep("code"); } catch(e){setError(e instanceof Error?e.message:"Registration could not start.");} finally{setBusy(false);} }
  async function verify(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form=new FormData(event.currentTarget); try { const result=await productRequest<{verificationToken:string}>(product,"/api/saas/auth/signup/verify",{method:"POST",body:JSON.stringify({product,challengeId,code:form.get("code")})},false); setVerificationToken(result.verificationToken); setStep("password"); } catch(e){setError(e instanceof Error?e.message:"Verification failed.");} finally{setBusy(false);} }
  async function complete(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form=new FormData(event.currentTarget); if(form.get("password")!==form.get("confirmPassword")){setError("Passwords do not match.");setBusy(false);return;} try { const result=await productRequest<{token:string}>(product,"/api/saas/auth/signup/complete",{method:"POST",body:JSON.stringify({product,challengeId,verificationToken,password:form.get("password")})},false); saveProductToken(product,result.token); router.push(config.basePath); } catch(e){setError(e instanceof Error?e.message:"Registration failed.");} finally{setBusy(false);} }
  return <Shell product={product} title="Start Your 30-Day Free Trial" text="Verify your business email, create your password and enter your product.">
    {step==="details"&&<form onSubmit={submitDetails} className="space-y-4"><Field name="ownerName" label="Your full name" autoComplete="name"/><Field name="businessName" label="Business name" autoComplete="organization"/><Field name="email" label="Valid email address" type="email" autoComplete="email"/><Field name="telephone" label="Telephone number" type="tel" autoComplete="tel"/><label className="block text-sm font-semibold">Business address<textarea name="businessAddress" required rows={3} className={inputClass}/></label><label className="flex items-start gap-3 text-xs leading-5 text-[#657074]"><input name="acceptedTerms" required type="checkbox" className="mt-1 accent-[#5e8983]"/>I agree to the Wedge Works Terms and Privacy Policy.</label><Action busy={busy} label="Send Verification Code"/></form>}
    {step==="code"&&<form onSubmit={verify} className="space-y-4"><p className="rounded-xl bg-[#5e8983]/10 p-4 text-sm text-[#35645e]">Check your email for the six-digit code. It expires in 10 minutes.</p><Field name="code" label="Verification code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6}/><Action busy={busy} label="Verify Email"/></form>}
    {step==="password"&&<form onSubmit={complete} className="space-y-4"><Field name="password" label="Create password" type="password" autoComplete="new-password" minLength={8}/><Field name="confirmPassword" label="Confirm password" type="password" autoComplete="new-password" minLength={8}/><Action busy={busy} label="Start Free Trial"/></form>}
    {error&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<p className="mt-5 text-center text-sm text-[#657074]">Already registered? <a href={`${config.basePath}/login`} className="font-bold text-[#497973]">Product Login</a></p>
  </Shell>;
}

export function ProductLoginPage({ product }: { product: PaidProduct }) {
  const router=useRouter();const config=productConfig[product];const [busy,setBusy]=useState(false);const[error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const result=await productRequest<{token:string}>(product,"/api/saas/auth/login",{method:"POST",body:JSON.stringify({product,email:form.get("email"),password:form.get("password")})},false);saveProductToken(product,result.token);router.push(config.basePath);}catch(e){setError(e instanceof Error?e.message:"Login failed.");}finally{setBusy(false);}}
  return <Shell product={product} title="Product Login" text="Enter your verified email and password."><form onSubmit={submit} className="space-y-4"><Field name="email" label="Email address" type="email" autoComplete="email"/><Field name="password" label="Password" type="password" autoComplete="current-password"/><div className="text-right"><a href={`${config.basePath}/forgot-password`} className="text-xs font-bold text-[#497973]">Forgot password?</a></div><Action busy={busy} label="Login"/>{error&&<p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<p className="text-center text-sm text-[#657074]">New business? <a href={`${config.basePath}/signup`} className="font-bold text-[#497973]">Start Free Trial</a></p></form></Shell>;
}

export function ProductForgotPasswordPage({product}:{product:PaidProduct}){
  const config=productConfig[product];const[step,setStep]=useState<"email"|"code"|"password"|"done">("email");const[challengeId,setChallengeId]=useState("");const[token,setToken]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  async function submit(path:string,body:Record<string,unknown>){setBusy(true);setError("");try{return await productRequest<Record<string,string>>(product,path,{method:"POST",body:JSON.stringify({product,...body})},false);}catch(e){setError(e instanceof Error?e.message:"Request failed.");return null;}finally{setBusy(false);}}
  return <Shell product={product} title="Reset Your Password" text="Use your verified business email to create a new password.">
    {step==="email"&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await submit("/api/saas/auth/password/start",{email:f.get("email")});if(r?.challengeId){setChallengeId(r.challengeId);setStep("code");}}} className="space-y-4"><Field name="email" label="Email address" type="email" autoComplete="email"/><Action busy={busy} label="Send Verification Code"/></form>}
    {step==="code"&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await submit("/api/saas/auth/password/verify",{challengeId,code:f.get("code")});if(r?.verificationToken){setToken(r.verificationToken);setStep("password");}}} className="space-y-4"><Field name="code" label="Verification code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6}/><Action busy={busy} label="Verify Code"/></form>}
    {step==="password"&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("password")!==f.get("confirm")){setError("Passwords do not match.");return;}const r=await submit("/api/saas/auth/password/complete",{challengeId,verificationToken:token,password:f.get("password")});if(r)setStep("done");}} className="space-y-4"><Field name="password" label="New password" type="password" minLength={8}/><Field name="confirm" label="Confirm password" type="password" minLength={8}/><Action busy={busy} label="Change Password"/></form>}
    {step==="done"&&<div className="text-center"><p className="rounded-xl bg-[#5e8983]/10 p-4 text-[#35645e]">Your password has been changed.</p><a href={`${config.basePath}/login`} className="mt-5 inline-block font-bold text-[#497973]">Return to Login</a></div>}{error&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  </Shell>;
}

type Plan={displayName:string;packageName:string;monthlyPrice:number;annualPrice:number;trialDays:number;currency:"MYR"};
export function ProductPaymentPage({product}:{product:PaidProduct}){const config=productConfig[product];const[plan,setPlan]=useState<Plan|null>(null);const[sub,setSub]=useState<ProductSubscription|null>(null);const[cycle,setCycle]=useState<"monthly"|"annual">("annual");const[method,setMethod]=useState<"card"|"fpx">("card");const[busy,setBusy]=useState(false);const[error,setError]=useState("");useEffect(()=>{Promise.all([productRequest<Plan>(product,`/api/saas/auth/public/plan?product=${product}`,{},false),productRequest<{subscription:ProductSubscription}>(product,"/api/saas/auth/session")]).then(([p,s])=>{setPlan(p);setSub(s.subscription);}).catch(e=>setError(e.message));},[product]);async function pay(){setBusy(true);setError("");try{const result=await productRequest<{checkoutUrl:string}>(product,"/api/payments/checkout/saas",{method:"POST",body:JSON.stringify({billingCycle:cycle,paymentMethod:method})});const url=new URL(result.checkoutUrl);if(url.protocol!=="https:")throw new Error("Invalid secure payment address.");window.location.assign(url.toString());}catch(e){setError(e instanceof Error?e.message:"Payment could not start.");setBusy(false);}}return <Shell product={product} title="Continue Subscription" text="Choose your package period and secure payment method."><div className="grid grid-cols-2 gap-3"><Choice active={cycle==="monthly"} onClick={()=>setCycle("monthly")} label="Monthly" value={plan?`RM ${plan.monthlyPrice.toFixed(2)}`:"—"}/><Choice active={cycle==="annual"} onClick={()=>setCycle("annual")} label="Annual" value={plan?`RM ${plan.annualPrice.toFixed(2)}`:"—"}/></div><p className="mt-6 text-sm font-bold">Payment method</p><div className="mt-2 grid grid-cols-2 gap-3"><Choice active={method==="card"} onClick={()=>setMethod("card")} label="Credit / debit card" value="Recurring"/><Choice active={method==="fpx"} onClick={()=>setMethod("fpx")} label="FPX online banking" value="One-time renewal"/></div>{sub&&<p className="mt-5 rounded-xl bg-[#20282c]/5 p-4 text-sm">Current status: <b>{sub.status.replaceAll("_"," ")}</b></p>}{error&&<p className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button onClick={pay} disabled={!plan||busy} className="mt-6 w-full rounded-xl bg-[#20282c] px-5 py-4 font-bold text-white disabled:opacity-50">{busy?"Opening secure payment...":"Proceed to Secure Payment"}</button><a href={config.basePath} className="mt-4 block text-center text-sm font-bold text-[#497973]">Return to {config.name}</a></Shell>;}

function Action({busy,label}:{busy:boolean;label:string}){return <button disabled={busy} className="w-full rounded-xl bg-[#20282c] px-5 py-4 font-bold text-white disabled:opacity-60">{busy?"Please wait...":label}</button>;}
function Choice({active,onClick,label,value}:{active:boolean;onClick:()=>void;label:string;value:string}){return <button type="button" onClick={onClick} className={`rounded-xl border p-4 text-left ${active?"border-[#5e8983] bg-[#5e8983]/10":"border-[#20282c]/10"}`}><span className="block text-sm font-bold">{label}</span><span className="mt-1 block text-xs text-[#657074]">{value}</span></button>;}
