export const metadata = {
  title: "Privacy Policy | WedgeCLOCKin",
  description:
    "Privacy Policy for the WedgeCLOCKin employee attendance and workforce management platform.",
};

const effectiveDate = "16 July 2026";

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-[#101416] px-6 py-12 text-[#f4efe6]">
      <article className="mx-auto max-w-4xl rounded-[2rem] border border-white/10 bg-[#1e2428] p-7 shadow-2xl sm:p-10">
        <header className="border-b border-white/10 pb-8">
          <p className="text-sm font-semibold tracking-[0.3em] text-[#d4ad63]">
            WEDGECLOCKIN
          </p>

          <h1 className="mt-4 text-4xl font-bold text-[#f0dfbd]">
            Privacy Policy
          </h1>

          <p className="mt-4 text-sm text-white/55">
            Effective date: {effectiveDate}
          </p>
        </header>

        <PolicySection title="1. Introduction">
          <p>
            WedgeCLOCKin is an employee attendance and workforce management
            service operated under the WedgeWorks brand. This Privacy Policy
            explains how WedgeCLOCKin accesses, collects, uses, stores,
            processes and protects information when companies, managers and
            employees use the WedgeCLOCKin mobile application, manager portal
            and related services.
          </p>
        </PolicySection>

        <PolicySection title="2. Information We Collect">
          <p>
            The information processed depends on the features enabled by the
            employer and may include:
          </p>

          <ul>
            <li>
              Account and profile information, including employee name,
              employee code, company code, department, position, telephone
              number and account credentials.
            </li>
            <li>
              Company information, including company name, registration
              information, workplace address and workplace GPS settings.
            </li>
            <li>
              Attendance records, including clock-in, rest-out, rest-in and
              clock-out dates and times.
            </li>
            <li>
              Location information collected during attendance actions to
              determine whether the employee is within the employer-approved
              workplace radius.
            </li>
            <li>
              Camera images and face-related information used to register and
              verify the employee during attendance.
            </li>
            <li>
              Leave applications, leave balances and approval records.
            </li>
            <li>
              Payroll and payslip information entered or generated by the
              employer, including salary, allowances, deductions, overtime and
              payroll remarks.
            </li>
            <li>
              Technical and security information needed to authenticate users,
              protect accounts, diagnose errors and maintain the service.
            </li>
          </ul>
        </PolicySection>

        <PolicySection title="3. Camera and AI Face Verification">
          <p>
            WedgeCLOCKin uses the device camera for employee face registration
            and attendance verification. A live attendance image may be
            compared with the employee&apos;s registered face information by
            an AI-assisted face-verification service.
          </p>

          <p>
            Face-related information is used for identity verification,
            attendance security and prevention of fraudulent or proxy
            attendance. It is not used for advertising and is not sold.
          </p>
        </PolicySection>

        <PolicySection title="4. Location Information">
          <p>
            WedgeCLOCKin may access precise device location when an employee
            performs an attendance action. The location is used to calculate
            whether the employee is inside the workplace radius configured by
            the employer.
          </p>

          <p>
            WedgeCLOCKin does not use attendance location information for
            advertising. Location access is requested through Android
            permission controls.
          </p>
        </PolicySection>

        <PolicySection title="5. How We Use Information">
          <ul>
            <li>Authenticate managers and employees.</li>
            <li>Register and verify employee identity.</li>
            <li>Record and validate attendance actions.</li>
            <li>Confirm workplace-radius compliance.</li>
            <li>Manage employee and company records.</li>
            <li>Process leave applications and balances.</li>
            <li>Prepare payroll records, payslips and exports.</li>
            <li>Prevent fraud, misuse and unauthorised access.</li>
            <li>Maintain, troubleshoot and improve the service.</li>
            <li>Comply with applicable legal obligations.</li>
          </ul>
        </PolicySection>

        <PolicySection title="6. Data Sharing and Service Providers">
          <p>
            WedgeCLOCKin does not sell personal information.
          </p>

          <p>
            Information may be processed by trusted service providers that
            support the operation of WedgeCLOCKin, including cloud hosting,
            database, authentication, deployment and AI-assisted verification
            providers. These providers process information only as necessary
            to provide their contracted services or where required by law.
          </p>

          <p>
            Information may also be disclosed where reasonably necessary to
            comply with applicable law, a lawful request, legal proceedings,
            security requirements or the protection of users and the service.
          </p>
        </PolicySection>

        <PolicySection title="7. Data Security">
          <p>
            WedgeCLOCKin uses reasonable technical and organisational measures
            to protect information, including encrypted HTTPS transmission,
            authenticated access, company-level data separation, access
            controls and protected cloud infrastructure.
          </p>

          <p>
            No internet-based system can guarantee absolute security. Managers
            and employees must protect their passwords and promptly report
            suspected unauthorised access.
          </p>
        </PolicySection>

        <PolicySection title="8. Data Retention">
          <p>
            Information is retained for as long as necessary to provide
            WedgeCLOCKin, maintain attendance and employment records, fulfil
            the employer&apos;s legitimate operational requirements, resolve
            disputes, prevent fraud and comply with applicable legal or
            regulatory obligations.
          </p>

          <p>
            Certain records may be retained for a legally required period even
            after an account-deletion request. Any retained information will
            remain protected and will not be used for unrelated purposes.
          </p>
        </PolicySection>

        <PolicySection title="9. Data Access, Correction and Deletion">
          <p>
            Employees may contact their employer or company manager to request
            access to, correction of or deletion of employee information.
            Company administrators may manage employee records through
            WedgeCLOCKin.
          </p>

          <p>
            Companies and users may also submit a privacy or deletion request
            using the contact information below. Where deletion is permitted,
            associated personal information will be deleted or anonymised,
            subject to legitimate security, employment-record and legal
            retention requirements.
          </p>
        </PolicySection>

        <PolicySection title="10. Employer Responsibilities">
          <p>
            Employers using WedgeCLOCKin are responsible for providing
            appropriate notices to employees, obtaining any consent required
            by applicable law, configuring workplace and attendance settings
            correctly, and ensuring they have a lawful basis to process
            employee information.
          </p>
        </PolicySection>

        <PolicySection title="11. Children">
          <p>
            WedgeCLOCKin is a business and employment-management service. It is
            not designed or directed toward children under 13.
          </p>
        </PolicySection>

        <PolicySection title="12. International Processing">
          <p>
            Cloud service providers may process information in locations other
            than the user&apos;s country. Where applicable, reasonable
            safeguards are used to protect information during such processing.
          </p>
        </PolicySection>

        <PolicySection title="13. Changes to This Policy">
          <p>
            This Privacy Policy may be updated when WedgeCLOCKin changes its
            services, data practices or legal obligations. The latest version
            will be published on this page with an updated effective date.
          </p>
        </PolicySection>

       <PolicySection title="14. Contact">
  <p>
    Questions about this Privacy Policy, privacy requests, or account
    deletion requests may be submitted through:
  </p>

  <div className="mt-4 rounded-2xl border border-[#d4ad63]/25 bg-[#101416] p-5">
    <p className="font-bold text-[#f0dfbd]">
      WedgeWorks
    </p>

    <p className="mt-2">
      Product: WedgeCLOCKin
    </p>

    <p className="mt-2">
      Website:&nbsp;
      <a
        href="https://www.wedge-works.com"
        className="text-[#d4ad63] underline"
      >
        https://www.wedge-works.com
      </a>
    </p>

    <p className="mt-2">
      Email:&nbsp;
      <a
        href="mailto:support@wedge-works.com"
        className="text-[#d4ad63] underline"
      >
        support@wedge-works.com
      </a>
    </p>

    <p className="mt-2">
      Business Hours: Monday – Friday, 9:00 AM – 6:00 PM (Malaysia Time)
    </p>
  </div>
</PolicySection>
        <footer className="mt-10 border-t border-white/10 pt-6 text-sm text-white/35">
          © {new Date().getFullYear()} WedgeWorks. All rights reserved.
        </footer>
      </article>
    </main>
  );
}

function PolicySection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-9">
      <h2 className="text-xl font-bold text-[#f0dfbd]">{title}</h2>

      <div className="mt-4 space-y-4 text-sm leading-7 text-white/65 [&_li]:ml-5 [&_li]:list-disc [&_ul]:space-y-2">
        {children}
      </div>
    </section>
  );
}