"use client";

import { useEffect, useState } from "react";

type Settings={defaultTrialDays:number;monthlyPrice:number;annualPrice:number;gracePeriodDays:number;registrationEnabled:boolean;beautyEnabled:boolean;petEnabled:boolean};
const empty:Settings={defaultTrialDays:30,monthlyPrice:0,annualPrice:0,gracePeriodDays:3,registrationEnabled:true,beautyEnabled:true,petEnabled:true};

export default function SmartPosControls(){
  const [settings,setSettings]=useState<Settings>(empty);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
  const api=process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/,"");
  useEffect(()=>{const token=localStorage.getItem("wc_manager_token");if(!api||!token){setMessage("SmartPOS backend connection is required before these controls can be published.");setLoading(false);return;}fetch(`${api}/api/founder/smartpos/settings`,{headers:{Authorization:`Bearer ${token}`}}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.message||"Could not load settings.");setSettings(body);}).catch(error=>setMessage(error.message)).finally(()=>setLoading(false));},[api]);
  function update<K extends keyof Settings>(key:K,value:Settings[K]){setSettings(current=>({...current,[key]:value}));setMessage("");}
  async function save(){const token=localStorage.getItem("wc_manager_token");if(!api||!token){setMessage("Backend connection is required.");return;}setSaving(true);setMessage("");try{const response=await fetch(`${api}/api/founder/smartpos/settings`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(settings)});const body=await response.json();if(!response.ok)throw new Error(body.message||"Could not save settings.");setSettings(body);setMessage("SmartPOS trial and pricing settings published successfully.");}catch(error){setMessage(error instanceof Error?error.message:"Save failed.");}finally{setSaving(false);}}
  return <section className="mt-7 rounded-[2rem] border border-[#5e8983]/30 bg-[#1e2428] p-6 sm:p-8"><div className="flex flex-col gap-3 border-b border-white/10 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold tracking-[.25em] text-[#79aaa3]">WEDGE-SMARTPOS CONTROLS</p><h2 className="mt-2 text-2xl font-bold text-[#f0dfbd]">Trial, pricing and registration</h2><p className="mt-2 text-sm text-white/45">These values apply globally. Existing merchant agreed prices remain unchanged.</p></div><span className="rounded-full bg-[#5e8983]/15 px-4 py-2 text-xs font-bold text-[#a7d0ca]">{loading?"Loading...":"Founder controlled"}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><NumberField label="Free trial days" value={settings.defaultTrialDays} step="1" onChange={value=>update("defaultTrialDays",Math.round(value))}/><NumberField label="Monthly price (RM)" value={settings.monthlyPrice} onChange={value=>update("monthlyPrice",value)}/><NumberField label="Annual price (RM)" value={settings.annualPrice} onChange={value=>update("annualPrice",value)}/><NumberField label="Grace period days" value={settings.gracePeriodDays} step="1" onChange={value=>update("gracePeriodDays",Math.round(value))}/></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Toggle label="Allow new registrations" checked={settings.registrationEnabled} onChange={value=>update("registrationEnabled",value)}/><Toggle label="Beauty & Wellness" checked={settings.beautyEnabled} onChange={value=>update("beautyEnabled",value)}/><Toggle label="Pet Care" checked={settings.petEnabled} onChange={value=>update("petEnabled",value)}/></div>{message&&<p className="mt-5 rounded-xl border border-[#d4ad63]/20 bg-[#d4ad63]/5 p-3 text-sm text-[#e4c98f]">{message}</p>}<button onClick={save} disabled={saving||loading} className="mt-5 rounded-full bg-[#5e8983] px-6 py-3 font-bold text-white disabled:opacity-50">{saving?"Publishing...":"Publish SmartPOS Settings"}</button></section>;
}
const input="mt-2 w-full rounded-xl border border-white/10 bg-[#101416] px-4 py-3 text-white outline-none focus:border-[#5e8983]";
function NumberField({label,value,onChange,step="0.01"}:{label:string;value:number;onChange:(value:number)=>void;step?:string}){return <label className="text-sm text-white/60">{label}<input type="number" min="0" step={step} value={value} onChange={event=>onChange(Math.max(0,Number(event.target.value)||0))} className={input}/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex items-center gap-3 rounded-xl border border-white/8 bg-black/10 p-4 text-sm text-white/60"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)} className="accent-[#5e8983]"/>{label}</label>}
