"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { smartPosRequest, type SmartPosPlan, type SmartPosSubscription } from "../lib/api";

export default function SmartPosPayment() {
  const [plan,setPlan]=useState<SmartPosPlan|null>(null); const [subscription,setSubscription]=useState<SmartPosSubscription|null>(null); const [cycle,setCycle]=useState<"monthly"|"annual">("annual"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>{ Promise.all([smartPosRequest<SmartPosPlan>("/api/smartpos/public/plan"),smartPosRequest<SmartPosSubscription>("/api/smartpos/subscription")]).then(([p,s])=>{setPlan(p);setSubscription(s);}).catch(e=>setError(e.message)); },[]);
  async function pay(){setBusy(true);setError("");try{const result=await smartPosRequest<{checkoutUrl:string}>("/api/smartpos/subscription/checkout",{method:"POST",body:JSON.stringify({billingCycle:cycle})});const checkoutUrl=new URL(result.checkoutUrl);if(checkoutUrl.protocol!=="https:")throw new Error("The secure payment address is invalid.");window.location.assign(checkoutUrl.toString());}catch(e){setError(e instanceof Error?e.message:"Payment could not start.");setBusy(false);}}
  return <main className="min-h-screen bg-[#f3efe7] px-5 py-12 text-[#20282c]"><div className="mx-auto max-w-4xl"><Link href="/wedge-smartpos" className="font-bold">← Wedge-SmartPOS</Link><div className="mt-8 grid overflow-hidden rounded-[30px] border border-[#20282c]/10 bg-white shadow-xl lg:grid-cols-[1fr_.8fr]"><section className="p-7 sm:p-10"><p className="text-xs font-bold tracking-[.22em] text-[#b08745]">SUBSCRIPTION</p><h1 className="mt-3 font-serif text-4xl">Continue using your POS</h1><p className="mt-4 leading-7 text-[#657074]">Your records remain safe. Select a plan to continue creating appointments and sales.</p><div className="mt-7 grid grid-cols-2 gap-3"><button onClick={()=>setCycle("monthly")} className={`rounded-xl border p-5 text-left ${cycle==="monthly"?"border-[#5e8983] bg-[#5e8983]/10":"border-[#20282c]/10"}`}><span className="block text-sm font-bold">Monthly</span><span className="mt-2 block text-2xl font-bold">{plan?`RM ${plan.monthlyPrice.toFixed(2)}`:"—"}</span></button><button onClick={()=>setCycle("annual")} className={`rounded-xl border p-5 text-left ${cycle==="annual"?"border-[#5e8983] bg-[#5e8983]/10":"border-[#20282c]/10"}`}><span className="block text-sm font-bold">Annual</span><span className="mt-2 block text-2xl font-bold">{plan?`RM ${plan.annualPrice.toFixed(2)}`:"—"}</span></button></div>{error&&<p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button onClick={pay} disabled={!plan||busy} className="mt-6 w-full rounded-xl bg-[#20282c] px-5 py-4 font-bold text-white disabled:opacity-50">{busy?"Opening secure payment...":"Proceed to Secure Payment"}</button></section><aside className="bg-[#132126] p-7 text-white sm:p-10"><p className="text-xs font-bold tracking-[.2em] text-[#d2aa62]">YOUR ACCOUNT</p><p className="mt-5 text-sm text-white/50">Current status</p><p className="mt-1 text-xl font-bold">{subscription?.status?.replaceAll("_"," ")||"Loading..."}</p>{subscription?.trialEndsAt&&<><p className="mt-6 text-sm text-white/50">Trial ends</p><p className="mt-1 font-semibold">{new Date(subscription.trialEndsAt).toLocaleDateString("en-MY",{dateStyle:"long"})}</p></>}<ul className="mt-8 space-y-3 text-sm text-white/65"><li>✓ Appointments and customer records</li><li>✓ POS sales and inventory</li><li>✓ Customer spending insights</li><li>✓ Business reports</li></ul></aside></div></div></main>;
}
