"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";

const inputClass="mt-2 w-full rounded-xl border border-white/10 bg-[#101416] px-4 py-3 text-white outline-none focus:border-[#d4ad63]";
async function request(path:string,body:unknown){const api=process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/,"");if(!api)throw new Error("API is not configured.");const response=await fetch(`${api}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.message||"Request failed.");return data;}
export default function ManagerForgotPassword(){const[step,setStep]=useState<"start"|"code"|"password"|"done">("start");const[challengeId,setChallengeId]=useState("");const[token,setToken]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function run(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"Request failed.");}finally{setBusy(false);}}return <main className="grid min-h-screen place-items-center bg-[#101416] px-5 text-white"><section className="w-full max-w-md rounded-[2rem] border border-[#d4ad63]/30 bg-[#1e2428] p-7"><p className="text-xs font-bold tracking-[.2em] text-[#d4ad63]">WEDGE CLOCK-IN</p><h1 className="mt-3 font-serif text-4xl text-[#f0dfbd]">Reset manager password</h1>{step==="start"&&<form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const r=await request("/api/auth/manager-password/start",{companyCode:f.get("companyCode"),email:f.get("email")});setChallengeId(r.challengeId);setStep("code");});}} className="mt-7 space-y-4"><Field name="companyCode" label="Company code"/><Field name="email" label="Verified business email" type="email"/><Action busy={busy} label="Send Verification Code"/></form>}{step==="code"&&<form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const r=await request("/api/auth/manager-password/verify",{challengeId,code:f.get("code")});setToken(r.verificationToken);setStep("password");});}} className="mt-7 space-y-4"><Field name="code" label="Six-digit code" inputMode="numeric" pattern="[0-9]{6}"/><Action busy={busy} label="Verify Code"/></form>}{step==="password"&&<form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("password")!==f.get("confirm")){setError("Passwords do not match.");return;}run(async()=>{await request("/api/auth/manager-password/complete",{challengeId,verificationToken:token,password:f.get("password")});setStep("done");});}} className="mt-7 space-y-4"><Field name="password" label="New password" type="password" minLength={8}/><Field name="confirm" label="Confirm password" type="password" minLength={8}/><Action busy={busy} label="Change Password"/></form>}{step==="done"&&<p className="mt-7 rounded-xl bg-emerald-500/10 p-4 text-emerald-200">Password changed successfully.</p>}{error&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}<Link href="/manager-login" className="mt-6 block text-center text-sm font-bold text-[#d4ad63]">Return to Manager Login</Link></section></main>;}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string;name:string}){const{label,...input}=props;return <label className="block text-sm font-semibold text-white/70">{label}<input {...input} required className={inputClass}/></label>;}
function Action({busy,label}:{busy:boolean;label:string}){return <button disabled={busy} className="w-full rounded-full bg-[#d4ad63] px-6 py-4 font-bold text-black disabled:opacity-60">{busy?"Please wait...":label}</button>;}
