import type { Metadata } from "next";
import LegalPage, { LegalSection } from "../components/LegalPage";

export const metadata: Metadata = {
  title: "Disclaimer | Wedge Works",
  description: "Important limitations and user responsibilities for Wedge Works products and outputs.",
};

const effectiveDate = "17 August 2026";

export default function DisclaimerPage() {
  return (
    <LegalPage
      title="Disclaimer"
      effectiveDate={effectiveDate}
      introduction="Wedge Works provides practical business software and decision-support tools. This page explains the limits of automated outputs, verification features and operational records."
    >
      <LegalSection title="1. Software and decision support only">
        <p>Wedge Works provides software tools. It does not act as your employer, accountant, auditor, tax agent, payroll bureau, lawyer, investment adviser, human-resources consultant, medical provider or other regulated professional. Information generated by the platform is not a substitute for qualified professional advice.</p>
      </LegalSection>
      <LegalSection title="2. Attendance, face and GPS verification">
        <p>Face comparison and workplace-radius checks are additional attendance controls, not an absolute guarantee of identity, physical presence, device integrity or employee conduct. Camera quality, lighting, connectivity, location accuracy, device settings and third-party verification services may affect results.</p>
        <p>Employers must review disputed punches, configure workplace coordinates and radius settings correctly, maintain fair correction procedures and avoid relying solely on an automated result for disciplinary action.</p>
      </LegalSection>
      <LegalSection title="3. Payroll, overtime and employment records">
        <p>Payroll, overtime, leave, statutory deductions and employment documents depend on customer inputs, settings and applicable law. Managers must review actual attendance, authorised OT, payable OT, replacement hours, wages, deductions and issued documents before relying on or distributing them. The platform does not guarantee legal or statutory compliance.</p>
      </LegalSection>
      <LegalSection title="4. Bookkeeping and OCR">
        <p>WedgeBooks may misread, omit or misclassify information from receipts, invoices, photographs or scans. Users must compare extracted information with the original source document before inserting it into a journal, exporting it or providing it to an accountant, auditor or tax authority. Source documents should be retained independently where required.</p>
      </LegalSection>
      <LegalSection title="5. AI, forecasts and recommendations">
        <p>Wedge-I and other AI-assisted features may generate forecasts, commentary, classifications and recommendations from incomplete or changing data. Outputs are estimates, may not reflect current conditions and do not promise any financial, commercial or operational outcome. Material decisions require human review and appropriate professional judgment.</p>
      </LegalSection>
      <LegalSection title="6. SmartPOS and operational systems">
        <p>Wedge-SmartPOS and Wedge-Supply ERP records depend on entries made by authorised users. Inventory, appointment, customer, commission, purchasing, production and sales information should be reconciled against physical stock, payment-provider records and business controls. Recording a payment method does not itself mean that Wedge Works processed or guaranteed payment unless a separate payment service is expressly integrated.</p>
      </LegalSection>
      <LegalSection title="7. WedgeWeb content and publication">
        <p>Users are responsible for website copy, images, claims, pricing, permissions, intellectual property, consumer disclosures and legal compliance. A preview or generated design does not guarantee accessibility, search ranking, sales, regulatory compliance or suitability for a particular business.</p>
      </LegalSection>
      <LegalSection title="8. Third-party services and availability">
        <p>Some functions rely on external hosting, databases, maps, email, AI, payment or messaging providers. Interruptions, policy changes, inaccurate external data or provider failures may affect the service. Wedge Works cannot guarantee the independent performance of third parties.</p>
      </LegalSection>
      <LegalSection title="9. No guaranteed outcome">
        <p>Use of Wedge Works does not guarantee increased revenue, reduced cost, legal compliance, accurate employee conduct, successful collections, uninterrupted operations or any other business outcome. Customers remain responsible for internal controls, backups, approvals, reconciliations and final decisions.</p>
      </LegalSection>
      <LegalSection title="10. Limitation and contact">
        <p>To the fullest extent permitted by law, Wedge Works is not responsible for losses caused by inaccurate customer inputs, unreviewed automated outputs, unauthorised account use, device or network conditions, third-party failures, or decisions made without appropriate review. This Disclaimer does not exclude rights or liability that cannot lawfully be excluded.</p>
        <p>Questions may be sent to <a href="mailto:support@wedge-works.com">support@wedge-works.com</a>.</p>
      </LegalSection>
    </LegalPage>
  );
}
