"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

const inputClass="mt-2 w-full rounded-xl border border-white/10 bg-[#101416] px-4 py-3 text-white outline-none focus:border-[#d4ad63]";
const api=()=>{const value=process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/,"");if(!value)throw new Error("API is not configured.");return value;};
async function request(path:string,body:unknown){const response=await fetch(`${api()}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.message||"Request failed.");return data;}

export default function ManagerSignup(){const router=useRouter();const[step,setStep]=useState<"details"|"code"|"password">("details");const[challengeId,setChallengeId]=useState("");const[token,setToken]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function run(fn:()=>Promise<void>){setBusy(true);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"Request failed.");}finally{setBusy(false);}}
  return <Shell title="Start Your 30-Day Free Trial" text="Register your company, verify its email and create the manager password.">
    {step==="details"&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const r=await request("/api/auth/manager-signup/start",{ownerName:f.get("ownerName"),companyName:f.get("companyName"),registrationNumber:f.get("registrationNumber"),companyCode:f.get("companyCode"),email:f.get("email"),phone:f.get("phone"),address:f.get("address"),acceptedTerms:f.get("acceptedTerms")==="on"});setChallengeId(r.challengeId);setStep("code");});}} className="space-y-4"><Field name="ownerName" label="Owner / manager full name"/><Field name="companyName" label="Company name"/><Field name="registrationNumber" label="Company registration number"/><Field name="companyCode" label="Company login code"/><Field name="email" label="Valid business email" type="email"/><Field name="phone" label="Telephone number" type="tel"/><label className="block text-sm font-semibold text-white/70">Business address<textarea name="address" required rows={3} className={inputClass}/></label><label className="flex gap-3 text-xs text-white/55"><input name="acceptedTerms" required type="checkbox" className="accent-[#d4ad63]"/>I agree to the Wedge Works Terms and Privacy Policy.</label><Action busy={busy} label="Send Verification Code"/></form>}
    {step==="code"&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const r=await request("/api/auth/manager-signup/verify",{challengeId,code:f.get("code")});setToken(r.verificationToken);setStep("password");});}} className="space-y-4"><p className="rounded-xl bg-white/5 p-4 text-sm text-white/60">Enter the six-digit code sent to your email.</p><Field name="code" label="Verification code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6}/><Action busy={busy} label="Verify Email"/></form>}
    {step==="password"&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("password")!==f.get("confirm")){setError("Passwords do not match.");return;}run(async()=>{const r=await request("/api/auth/manager-signup/complete",{challengeId,verificationToken:token,password:f.get("password")});localStorage.setItem("wc_manager_token",r.token);localStorage.setItem("wc_company_id",r.companyId);localStorage.setItem("wc_company_code",r.companyCode);localStorage.setItem("wc_company_name",r.companyName||"");localStorage.setItem("wc_manager_id",r.managerId||"");router.push("/manager-dashboard");});}} className="space-y-4"><Field name="password" label="Create manager password" type="password" minLength={8}/><Field name="confirm" label="Confirm password" type="password" minLength={8}/><Action busy={busy} label="Start Free Trial"/></form>}
    {error&&<p className="mt-4 rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}<p className="mt-5 text-center text-sm text-white/50">Already registered? <Link href="/manager-login" className="font-bold text-[#d4ad63]">Manager Login</Link></p>
  </Shell>;
}
function Shell({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <main className="min-h-screen bg-[#101416] px-5 py-10 text-[#f4efe6]"><div className="mx-auto max-w-lg"><Link href="/" className="mb-8 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#d4ad63] font-black text-black">W</span><b>Wedge Clock-In</b></Link><section className="rounded-[2rem] border border-[#d4ad63]/30 bg-[#1e2428] p-7 shadow-2xl"><p className="text-xs font-bold tracking-[.22em] text-[#d4ad63]">MANAGER ACCESS</p><h1 className="mt-3 font-serif text-4xl text-[#f0dfbd]">{title}</h1><p className="mt-3 text-sm leading-6 text-white/55">{text}</p><div className="mt-7">{children}</div></section></div></main>;}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string;name:string}){const{label,...input}=props;return <label className="block text-sm font-semibold text-white/70">{label}<input {...input} required className={inputClass}/></label>;}
function Action({busy,label}:{busy:boolean;label:string}){return <button disabled={busy} className="w-full rounded-full bg-[#d4ad63] px-6 py-4 font-bold text-black disabled:opacity-60">{busy?"Please wait...":label}</button>;}
